url: https://johnghiz.ca
baseurl:

# Site settings
title: John Ghiz
email: john.ghiz@gmail.com
phone: 647-210-8370
address: Montreal, Canada
description: "Writer, Actor, Voice-Over Artist"
og_image: /img/og_image.jpg
# links
imdb: https://imdb.me/johnghiz
resume: https://resumes.actorsaccess.com/johnghiz

# seo
author: John Ghiz
twitter: "@JohnGhiz"

# Team names, titles and social links
people:
- name: John Ghiz
  pic: JG
  position: Actor, Writer, Voice-Over Artist
  social:
    - title: imdb
      title_icon: fab fa-imdb
      url: https://imdb.me/johnghiz
    - title: instagram
      title_icon: fab fa-instagram-square
      url: https://www.instagram.com/john_ghiz/?hl=en
    - title: twitter
      title_icon: fab fa-twitter-square
      url: https://twitter.com/JohnGhiz
    - title: linkedin
      title_icon: fab fa-linkedin
      url: https://www.linkedin.com/in/john-ghiz-041b0399/


# Build settings
markdown: kramdown
permalink: pretty

include:
  - _pages

plugins:
  - jekyll-sitemap

theme: jekyll-theme-cayman

# Gallery Images
carousel:
  - url: /img/JG Mic.jpg
    alt: John in the studio
  - url: /img/bike.jpg
    alt: Bicycle
  - url: /img/gunpoint.jpg
    alt: John acting
  - url: /img/Writing and Editing.jfif
    alt: Typewriter
  - url: /img/og_image_1.jpg
    alt: John Ghiz
  - url: /img/JG.jpg
    alt: John Ghiz